### ISSUE TITLE
How to host a reveal.js presentation

### ISSUE THREAD

**Issue by witszymanski** [dougmvieira/presentations#1]
Hi! 
I followed your steps, however, my rendering didn't really work as it should. This is what I get:
[what I get][1]

I should get this:
[desired output][2]

Any ideas, where I am making a mistake? 

  [1]: https://i.stack.imgur.com/6Gfij.png
  [2]: https://i.stack.imgur.com/0fAh6.png

Greets!
Witek

**Comment by witszymanski** [comment]
Solved!! I spent the whole day but solved. 1 or 2 lines were missing in the YAML. I think this should be included in all the tutorials, or I am a noob: 
```

format: 
  revealjs:
    self-contained: true
    embed-resources: true
```

Greets! Thanks for the rest of the tutorial! Now I can make a repository with my presentations. Awesome!
